### ISSUE TITLE
Add support for param tags in launch file parser

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/roswire#257]
* [x] #259 load parameter values
* [x] #261 resolve parameter names
* [x] #262 add parameters to configuration
