### ISSUE TITLE
Add proxy for interacting with file system

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/roswire#7]
* [x] #53 read contents of file
* [x] #55 write to file
* [ ] append to file
* [ ] #181 implement `find`-like functionality
* [ ] copy file (i.e., `shutil.copy`)
* [ ] copy tree recursively (i.e., `shutil.copytree`)
* [ ] #47 chmod (i.e., `os.chmod`)
* [x] #40 remove file (i.e., `os.remove`, `rm`)
* [x] #41 remove directory (i.e., `os.rmdir`, `rmdir`)
* [x] #44 remove directory and contents (i.e., `shutil.rmtree`, `rm -r`)
* [x] #35 list contents of directory (i.e., `os.listdir`, `ls`)
* [x] #36 create directory (non-recursive) (i.e., `os.mkdir`)
* [x] #39 create directory (recursive) (i.e., `os.makedirs`)
* [x] #34 check if file/directory exists (i.e., `os.exists`, `os.isfile`, `os.isdir`, `os.islink`)
* [ ] #48 touch (i.e., `os.touch`)
* [x] #50 copy to host (i.e., `docker cp`)
* [x] #51 copy from host (i.e., `docker cp`)
* [x] #121 create temporary file (i.e., `tempfile.mktemp`)
* [ ] #122 create temporary directory (i.e., `tempfile.mkdtemp`)
* [x] #123 temporary file context manager
* [ ] #125 temporary dir context manager

## References
https://docs.python.org/3/library/os.html
https://docs.python.org/3/library/shutil.html

**Comment by ChrisTimperley** [comment]
ShellProxy and FilesystemProxy responsibilities been moved to https://github.com/ChrisTimperley/DockerBlade
